apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: auction-namespace
spec:
  type: LoadBalancer
  selector:
    app: auction-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5248
