apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: auction-namespace
  labels:
    app: auction-deployment
spec:
  type: LoadBalancer  # Use LoadBalancer type
  selector:
    app: auction-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80