apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: auction-namespace
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: oleksandrdotnet777/payment-web:latest
          ports:
            - containerPort: 7235
            - containerPort: 5225
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5225"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: auction-secrets
                  key: PostgresConnectionString
