apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-gateway
  namespace: auction-namespace
  labels:
    app: auction-gateway
    app-group: auction-apps  # Common label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-gateway
  template:
    metadata:
      labels:
        app: auction-gateway
        app-group: auction-apps  # Common label
    spec:
      containers:
        - name: auction-gateway
          image: oleksandrdotnet777/auction-gateway:latest
          ports:
            - containerPort: 7112
            - containerPort: 5167
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5167"
            - name: ReverseProxy__Clusters__auth-cluster__Destinations__auth-destination__Address
              value: "http://auction-auth:5190"
            - name: ReverseProxy__Clusters__auction-cluster__Destinations__auction-destination__Address
              value: "http://auction-service:5248"
            - name: ReverseProxy__Clusters__payment-cluster__Destinations__auth-destination__Address
              value: "http://payment-service:5225"  # Update this if you have a different service for payments
