apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: auction-namespace
  labels:
    app: react-app
    app-group: auction-apps  # Common label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
        app-group: auction-apps  # Common label
    spec:
      containers:
        - name: react-app
          image: oleksandrdotnet777/react-app:20240131161413  # Replace with your Docker image and tag
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              value: "development"
            - name: VITE_GATEWAY_URL
              value: "http://184.72.108.154:30012" # external address of api gateway. TODO: Fix it to use internal
