apiVersion: v1
kind: Secret
metadata:
  name: auction-secrets
  namespace: auction-namespace
data:
  PostgresConnectionString: SG9zdD1hdWN0aW9uLWRiLWRldi5jZGF3dTIwa2cyNWMudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tO1BvcnQ9NTQzMjtEYXRhYmFzZT1BdWN0aW9uO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPUFzc2Fzc2luczIwMDIkOw==

