name: Build and Test .NET Microservices

on:
  push:
    branches:
      - dev
  workflow_dispatch: {} # Allow manual triggering

jobs:
  build_auth_web:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Use the desired .NET Core 8 version

      - name: Build Auth.Web
        working-directory: Auth.Web
        run: |
          dotnet build # Use appropriate build command for Auth.Web

      - name: Build Docker Image for Auth.Web
        working-directory: Auth.Web
        run: |
          docker build -t auth-web .
          # Use the appropriate Docker build command for Auth.Web

  build_auction_web:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Use the desired .NET Core 8 version

      - name: Build Auction.Web
        working-directory: Auction.Web
        run: |
          dotnet build # Use appropriate build command for Auction.Web

      - name: Build Docker Image for Auction.Web
        working-directory: Auction.Web
        run: |
          docker build -t auction-web .
          # Use the appropriate Docker build command for Auction.Web
