name: Payment service

on:
  push:
    branches:
      - dev
  workflow_dispatch: {} # Allow manual triggering

jobs:
  build_payment_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Use the desired .NET Core 8 version

      - name: Build Payment.Web
        run: |
          cd Payment.Web # Set the working directory to Payment.Web
          dotnet build # Use appropriate build command for Payment.Web

      - name: Build Docker Image for Payment.Web
        run: |
          docker build -t payment-web -f PaymentDockerfile .

      - name: Publish Docker Image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker tag payment-web ${{ secrets.DOCKER_HUB_USERNAME }}/payment-web:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/payment-web:latest
